-- MySQL Script generated by MySQL Workbench
-- 01/04/18 21:36:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema openfoodfacts_oc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `openfoodfacts_oc` ;

-- -----------------------------------------------------
-- Schema openfoodfacts_oc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `openfoodfacts_oc` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `openfoodfacts_oc` ;

-- -----------------------------------------------------
-- Table `openfoodfacts_oc`.`Category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `openfoodfacts_oc`.`Category` ;

CREATE TABLE IF NOT EXISTS `openfoodfacts_oc`.`Category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openfoodfacts_oc`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `openfoodfacts_oc`.`Product` ;

CREATE TABLE IF NOT EXISTS `openfoodfacts_oc`.`Product` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` BIGINT(20) NOT NULL,
  `url` VARCHAR(1000) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `nutri_grade` CHAR(1) NULL,
  `cat_id` INT UNSIGNED NOT NULL,
  `energy` INT NULL,
  `fat` DOUBLE NULL,
  `carbs` DOUBLE NULL,
  `sugars` DOUBLE NULL,
  `salt` DOUBLE NULL,
  `fibers` DOUBLE NULL,
  `proteins` DOUBLE NULL,
  `last_modified_datetime` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Products_Categories_idx` (`cat_id` ASC),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  CONSTRAINT `fk_cat_id`
    FOREIGN KEY (`cat_id`)
    REFERENCES `openfoodfacts_oc`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openfoodfacts_oc`.`Favorite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `openfoodfacts_oc`.`Favorite` ;

CREATE TABLE IF NOT EXISTS `openfoodfacts_oc`.`Favorite` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `product_id` INT UNSIGNED NOT NULL,
  `substitute_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_Favorites_Products1_idx` (`product_id` ASC),
  INDEX `fk_Favorites_Products2_idx` (`substitute_id` ASC),
  CONSTRAINT `fk_Favorites_Products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `openfoodfacts_oc`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favorites_Products2`
    FOREIGN KEY (`substitute_id`)
    REFERENCES `openfoodfacts_oc`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openfoodfacts_oc`.`Store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `openfoodfacts_oc`.`Store` ;

CREATE TABLE IF NOT EXISTS `openfoodfacts_oc`.`Store` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openfoodfacts_oc`.`Brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `openfoodfacts_oc`.`Brand` ;

CREATE TABLE IF NOT EXISTS `openfoodfacts_oc`.`Brand` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openfoodfacts_oc`.`ProductBrand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `openfoodfacts_oc`.`ProductBrand` ;

CREATE TABLE IF NOT EXISTS `openfoodfacts_oc`.`ProductBrand` (
  `brand_id` INT UNSIGNED NOT NULL,
  `product_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`brand_id`, `product_id`),
  INDEX `fk_ProductsBrands_Brands1_idx` (`brand_id` ASC),
  INDEX `fk_ProductsBrands_Products1_idx` (`product_id` ASC),
  CONSTRAINT `fk_ProductsBrands_Brands1`
    FOREIGN KEY (`brand_id`)
    REFERENCES `openfoodfacts_oc`.`Brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductsBrands_Products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `openfoodfacts_oc`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `openfoodfacts_oc`.`ProductStore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `openfoodfacts_oc`.`ProductStore` ;

CREATE TABLE IF NOT EXISTS `openfoodfacts_oc`.`ProductStore` (
  `product_id` INT UNSIGNED NOT NULL,
  `store_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`product_id`, `store_id`),
  INDEX `fk_ProductsStores_Products1_idx` (`product_id` ASC),
  INDEX `fk_ProductsStores_Stores1_idx` (`store_id` ASC),
  CONSTRAINT `fk_ProductsStores_Products1`
    FOREIGN KEY (`product_id`)
    REFERENCES `openfoodfacts_oc`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductsStores_Stores1`
    FOREIGN KEY (`store_id`)
    REFERENCES `openfoodfacts_oc`.`Store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
